version: "3.1"

services:
  redmine:
    image: redmine:latest
    restart: unless-stopped
    volumes:
      - ./redmine-data:/usr/src/redmine/files
    ports:
      - "8200:3000"
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD=ali123456
      - REDMINE_SECRET_KEY_BASE=supersecretkey
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ali123456
      - MYSQL_DATABASE=redmine
